### ISSUE TITLE
FsUnit 4.0 Roadmap

### ISSUE THREAD

**Issue by sergey-tihon** [fsprojects/FsUnit#158]
- [x] Merge https://github.com/fsprojects/FsUnit/pull/147
   - [x] Find out why Equality.fs printf to console. https://github.com/fsprojects/FsUnit/pull/160
- [x] Merge https://github.com/fsprojects/FsUnit/pull/157
   - [x] https://github.com/fsprojects/fantomas/issues/982
- [x] Format `tests/**` using Fantomas - https://github.com/fsprojects/FsUnit/pull/159
- [x] Update docs
   - [x] Remove http://fsprojects.github.io/FsUnit/Paket.html
   - [x] Remove paket guide from  http://fsprojects.github.io/FsUnit/FsUnitTyped.html
- [x] move to `fsdocs` https://github.com/fsprojects/FsUnit/pull/168
   - [x] Merge https://github.com/fsprojects/FsUnit/pull/164
- [x] Remove MbUnit from logo
- [x] DisableImplicitFrameworkReferences for DesignTimeBuild #161
- [x] Upgrade FSharp.Core to 4.3.4 https://github.com/fsprojects/FsUnit/pull/162
- [x] Drop net46 support - https://github.com/fsprojects/FsUnit/pull/169

**Comment by sergey-tihon** [comment]
@CaptnCodr anything else that should be here or potentially breaking?

**Comment by CaptnCodr** [comment]
1. Will the Nuget package "Fs30Unit.MsTest" changed to "FsUnit.MsTest" (https://github.com/fsprojects/FsUnit/pull/157/commits/78f6a062c51da98c0102254974e5f325c019b982) and have to be mentioned in the release notes?
2. What about the "issue" with the `dot` in Visual Studio what I mentioned here: https://github.com/fsprojects/FsUnit/pull/157#issuecomment-657123966
to have better structured tests in the test explorer?
3. I opened another PR (#161) that removes some warnings but we have yellow triangles in the solution explorer (as shown below) -> you not? We could consider to look into this to have clean references.

![image](https://user-images.githubusercontent.com/4574031/87884524-08d94b80-ca0f-11ea-9172-2b0bb63db417.png)

4. Clean up repo issues, perhaps? -> Old/abandoned, resolved-ish and declined issues.

**Comment by CaptnCodr** [comment]
@sergey-tihon Why did you revert the Fsharp.Core version yesterday? (https://github.com/fsprojects/FsUnit/commit/c4bd0c9de05259a8b78488dadd4a3bf4fc2e8576) Are there any issues then?

**Comment by sergey-tihon** [comment]
> Will the Nuget package "Fs30Unit.MsTest" changed to "FsUnit.MsTest" (78f6a06) and have to be mentioned in the release notes?

NuGet package is not renamed yet. It is build from paket template that still has old name  - https://github.com/fsprojects/FsUnit/blob/master/src/FsUnit.MsTestUnit/paket.template#L3
I am not fully sure that we should rename ... Rename means new package publishing with 0 downloads and breaking change for all existing users...

> What about the "issue" with the dot in Visual Studio what I mentioned here: #157 (comment)
to have better structured tests in the test explorer?

I can merge PR with some consistent unit test naming...
Do you have issue reported to VS test explorer about [dot] in test names?

> Why did you revert the Fsharp.Core version yesterday? (c4bd0c9) Are there any issues then?

[Libraries should target lower versions of FSharp.Core](https://fsharp.github.io/2015/04/18/fsharp-core-notes.html#libraries-should-target-lower-versions-of-fsharpcore)

`v4.2.3` is lowest version that allow us target 2 runtimes and there is no real need to force all our users to update FSharp.Core to latest version in their solutions. (Version of our dependency defines min supported version in NuGet packages)

**Comment by CaptnCodr** [comment]
> NuGet package is not renamed yet. It is build from paket template that still has old name
Then we shouldn't do that now.

> Do you have issue reported to VS test explorer about [dot] in test names?
`[dot]` should go. I read a few times that people do that with `[dot]` instead of `.`.

> Libraries should target lower versions of FSharp.Core
I didn't know.

**Comment by sergey-tihon** [comment]
> [dot] should go. I read a few times that people do that with [dot] instead of ..

@CaptnCodr do you to want PR consistent renaming that works for you in VS?

**Comment by CaptnCodr** [comment]
Yes, of course.

**Comment by CaptnCodr** [comment]
Btw.: After pulling master I got this warnings again:
![image](https://user-images.githubusercontent.com/4574031/87906389-da855b80-ca62-11ea-8149-36c45787de2b.png)

**Comment by CaptnCodr** [comment]
From the checks above:

> Remove MbUnit from logo

We could add the new logo to the fsharp.org projects page:
https://fsharp.org/community/projects/

**Comment by CaptnCodr** [comment]
To my comment above:
> 4. Clean up / evaluate repo issues, perhaps? -> Old/abandoned, resolved-ish and declined issues.

Here is what I think:

#19 -> abandoned / wrong repo
#47 -> not idiomatic / declined
#72 -> old / resolved?
#109 -> resolved?
#111 -> abandoned
#121 -> not up-to-date / abandoned
#124 -> resolved
#151 -> not idiomatic
#153 -> resolved
#154 -> resolved

**Comment by CaptnCodr** [comment]
Nice work! 🙂

**Comment by sergey-tihon** [comment]
@CaptnCodr thank you for your help
